language: python
python:
- '2.7'

install:
- pip install pelican markdown ghp-import typogrify pygments

script:
# /home/travis/build/rickhau/rickhau.github.io/
# git clone https://github.com/fle/pelican-simplegrey.git
- git clone https://github.com/getpelican/pelican-plugins.git
- git clone https://github.com/getpelican/pelican-themes/pelican-bootstrap3.git
- make travis
