language: python
python:
- '2.7'

install:
- sudo apt-get install libjpeg libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev
- pip install pelican markdown ghp-import typogrify pygments PIL

script:
# /home/travis/build/rickhau/rickhau.github.io/
# git clone https://github.com/fle/pelican-simplegrey.git
- git clone https://github.com/getpelican/pelican-plugins.git
- git clone https://github.com/fle/pelican-sober.git
- make travis
